// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1dH95mxUHuTgbZv45vAZSS5EHVSbJ2Dc',
    appId: '1:974251935497:android:8dbc8b8ce150eefe9b35d8',
    messagingSenderId: '974251935497',
    projectId: 'cray-tech-project-ecom',
    databaseURL: 'https://cray-tech-project-ecom-default-rtdb.firebaseio.com',
    storageBucket: 'cray-tech-project-ecom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4DgjTtTfJ6y6Rc_5pZ485oeivNWCXnOQ',
    appId: '1:974251935497:ios:92742e27d9e1a9cc9b35d8',
    messagingSenderId: '974251935497',
    projectId: 'cray-tech-project-ecom',
    databaseURL: 'https://cray-tech-project-ecom-default-rtdb.firebaseio.com',
    storageBucket: 'cray-tech-project-ecom.appspot.com',
    androidClientId: '974251935497-qmckvl4bflj4uegl1s2igenbghve451h.apps.googleusercontent.com',
    iosClientId: '974251935497-0sr7cjr1pg1u9dts2bes052u0lfpq16a.apps.googleusercontent.com',
    iosBundleId: 'com.hiran.ecom',
  );

}